In [33]:
'Question 1'
myList = [2002]
n = 2002
while n +7<= 3200:
    n += 7
    myList.append(n)
print( myList)

[2002, 2009, 2016, 2023, 2030, 2037, 2044, 2051, 2058, 2065, 2072, 2079, 2086, 2093, 2100, 2107, 2114, 2121, 2128, 2135, 2142, 2149, 2156, 2163, 2170, 2177, 2184, 2191, 2198, 2205, 2212, 2219, 2226, 2233, 2240, 2247, 2254, 2261, 2268, 2275, 2282, 2289, 2296, 2303, 2310, 2317, 2324, 2331, 2338, 2345, 2352, 2359, 2366, 2373, 2380, 2387, 2394, 2401, 2408, 2415, 2422, 2429, 2436, 2443, 2450, 2457, 2464, 2471, 2478, 2485, 2492, 2499, 2506, 2513, 2520, 2527, 2534, 2541, 2548, 2555, 2562, 2569, 2576, 2583, 2590, 2597, 2604, 2611, 2618, 2625, 2632, 2639, 2646, 2653, 2660, 2667, 2674, 2681, 2688, 2695, 2702, 2709, 2716, 2723, 2730, 2737, 2744, 2751, 2758, 2765, 2772, 2779, 2786, 2793, 2800, 2807, 2814, 2821, 2828, 2835, 2842, 2849, 2856, 2863, 2870, 2877, 2884, 2891, 2898, 2905, 2912, 2919, 2926, 2933, 2940, 2947, 2954, 2961, 2968, 2975, 2982, 2989, 2996, 3003, 3010, 3017, 3024, 3031, 3038, 3045, 3052, 3059, 3066, 3073, 3080, 3087, 3094, 3101, 3108, 3115, 3122, 3129, 3136, 3143, 3150, 3157, 316

In [34]:
'Question 2'
nbr = int(input('Entrez un nombre : '))
fact = 1
for i in range(1, nbr+1):
  fact = fact * i
print (nbr,'! = ',fact)

Entrez un nombre : 8
8 ! =  40320


In [19]:
'Question 3'
nbr = int(input('Entrez un nombre : '))
my_dict = {}
for i in range(1,nbr+1):
    my_dict[i] = i*i
print(my_dict)

Entrez un nombre : 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [26]:
'Question 4'
myList= [str(input('Entrez une chaine : '))]
s=myList[0]
nb = -1
while not int(nb) in range(0,len(s)):
    nb =int(input('Entrez un nombre : '))
myList.append(nb)
i=myList[1]
print("missing_char('",s,"',", 1,") → ",s.replace(s[i],""))

Entrez une chaine : Kitten
Entrez un nombre : 1
missing_char(' Kitten ', 1 ) →  Ktten


In [28]:
'Question 5'
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [29]:
'Question 6'
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [32]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list) 

Provide D:  100,150,180 
[18, 22, 24]
